CREATE TABLE LICENCE ( ID INTEGER PRIMARY KEY AUTOINCREMENT , EXPIRY_DATE INTEGER NULL, ISSUE_DATE INTEGER NULL, LICENCE_NUMBER TEXT )
CREATE TABLE LICENCE_VEHICLE_CLASS ( ID INTEGER PRIMARY KEY AUTOINCREMENT , CODE TEXT, DATE_OF_ISSUE INTEGER NULL, DESCRIPTION TEXT, LICENCE INTEGER )
CREATE TABLE VEHICLE ( ID INTEGER PRIMARY KEY AUTOINCREMENT , COLOR TEXT, MAKE TEXT, NUMBER TEXT, NUMBER_PREFIX TEXT, STATE_CODE TEXT, UNIQUE (NUMBER,NUMBER_PREFIX,STATE_CODE) )
CREATE TABLE OFFENCE ( ID INTEGER PRIMARY KEY AUTOINCREMENT , CODE TEXT, LICENSEE INTEGER )
CREATE TABLE OFFENCE_TYPE ( ID INTEGER PRIMARY KEY AUTOINCREMENT , code TEXT, description TEXT )
CREATE TABLE LICENSEE ( ID INTEGER PRIMARY KEY AUTOINCREMENT , LICENCE INTEGER, PERSONAL_DETAILS INTEGER )
CREATE TABLE PERSONAL_DETAILS ( ID INTEGER PRIMARY KEY AUTOINCREMENT , DATE_OF_BIRTH INTEGER NULL, FIRST_NAME TEXT, LAST_NAME TEXT, MIDDLE_NAME TEXT )
CREATE TABLE TRAFFIC_POLICE ( ID INTEGER PRIMARY KEY AUTOINCREMENT , id_number TEXT, PERSONAL_DETAILS INTEGER )



Select * from licensee inner join licence on licensee.licence = licence.id where licence_number like '';